### ISSUE TITLE
Linux Java 17 build fails since I20230116-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#183]
See 
- https://download.eclipse.org/eclipse/downloads/drops4/I20230116-1800/testResults.php
- https://ci.eclipse.org/releng/view/Automated%20tests/job/AutomatedTests/job/ep427I-unit-cen64-gtk3-java17/61/console
- https://ci.eclipse.org/releng/view/Automated%20tests/job/AutomatedTests/job/ep427I-unit-cen64-gtk3-java17/62/console
```
Jan 17, 2023 12:34:06 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://jenkins-ui.releng.svc.cluster.local/releng/tcpSlaveAgentListener/: jenkins-ui.releng.svc.cluster.local
java.io.IOException: Failed to connect to http://jenkins-ui.releng.svc.cluster.local/releng/tcpSlaveAgentListener/: jenkins-ui.releng.svc.cluster.local
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
	at hudson.remoting.Engine.innerRun(Engine.java:745)
	at hudson.remoting.Engine.run(Engine.java:544)
Caused by: java.net.UnknownHostException: jenkins-ui.releng.svc.cluster.local
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:276)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:375)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:396)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:211)
	... 2 more
```

**Comment by akurtakov** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2478

**Comment by akurtakov** [comment]
This issue is coming and going for the last week. Not much to do

**Comment by iloveeclipse** [comment]
@SDawley : thanks for opening gitlab issue. 
Please next time you open build related gitlab ticket, could you open a ticket here or just send a mail to platform releng list about observed issue? So others don't need to spend time searching through log files etc for possible root cause?

**Comment by iloveeclipse** [comment]
Seem to work now. Will open another ticket for Windows builds not running since days...
