### ISSUE TITLE
DNF in most Linux test suites with I20230314-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#210]
Common thing **seem** to be some low level SWT issue:

- https://download.eclipse.org/eclipse/downloads/drops4/I20230314-1800/testresults/ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/org.eclipse.jdt.debug.tests.AutomatedSuite.txt
- https://download.eclipse.org/eclipse/downloads/drops4/I20230314-1800/testresults/ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/org.eclipse.debug.tests.AutomatedSuite.txt
- 
```
!ENTRY org.eclipse.jface 2 0 2023-03-15 00:23:12.170
!MESSAGE The image could not be loaded: URLImageDescriptor(platform:/plugin/org.eclipse.e4.ui.workbench.renderers.swt/icons/full/ovr16/pinned_ovr.png)
!STACK 0
org.eclipse.jface.resource.DeviceResourceException: Unable to create resource URLImageDescriptor(platform:/plugin/org.eclipse.e4.ui.workbench.renderers.swt/icons/full/ovr16/pinned_ovr.png)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:232)
	at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:55)
	at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:88)
	at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:103)
	at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:195)
	at org.eclipse.jface.resource.ImageRegistry.get(ImageRegistry.java:206)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.getImageFromURI(SWTPartRenderer.java:228)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.init(SWTPartRenderer.java:326)
	at org.eclipse.e4.ui.workbench.renderers.swt.WorkbenchRendererFactory.initRenderer(WorkbenchRendererFactory.java:145)
	at org.eclipse.e4.ui.workbench.renderers.swt.WorkbenchRendererFactory.getRenderer(WorkbenchRendererFactory.java:135)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.getRenderer(PartRenderingEngine.java:1024)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:991)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
```

I don't see breaking changes in SWT or platform UI itself, so **probably** related to the new container build, see 
- https://www.eclipse.org/lists/platform-releng-dev/msg39195.html
- https://ci.eclipse.org/releng/job/Build-Docker-images/498/console

**Comment by laeubi** [comment]
I think this is really a case where delegation to an existing method works bad... JFace is encountering some error but does not propagate it... I think the first step would be to enhance the error reporting here.

**Comment by trancexpress** [comment]
The SWT build failed? If I compare the output of the docker console I see in job 498:

```
08:39:21  + docker images
08:39:21  REPOSITORY                                    TAG       IMAGE ID       CREATED          SIZE
08:39:21  eclipse/platformreleng-centos-gtk3-metacity   8         8fbce9126b37   52 seconds ago   946MB
08:39:21  eclipse/platformreleng-ubuntu-gtk3-metacity   jikespg   d70fa3d43a3a   4 minutes ago    413MB
08:39:21  <none>                                        <none>    2678c39f8bf4   8 minutes ago    374MB
08:39:21  <none>                                        <none>    5b4f5381b528   8 minutes ago    77.8MB
08:39:21  <none>                                        <none>    a7d8a1f29439   8 minutes ago    155MB
08:39:21  <none>                                        <none>    2caea9f4aae3   8 minutes ago    204MB
08:39:21  <none>                                        <none>    64767fad4408   8 minutes ago    155MB
08:39:21  <none>                                        <none>    a740c8b4da62   8 minutes ago    72.8MB
08:39:21  <none>                                        <none>    adce61e8f58d   8 minutes ago    63.1MB
08:39:21  <none>                                        <none>    3e0ba40162a9   8 minutes ago    113MB
08:39:21  quay.io/centos/centos                         stream9   59e5be04c9f7   5 days ago       155MB
08:39:21  ubuntu                                        20.04     61c45d0e9798   13 days ago      72.8MB
08:39:21  ubuntu                                        22.04     74f2314a03de   13 days ago      77.8MB
08:39:21  ubuntu                                        18.04     b89fba62bc15   13 days ago      63.1MB
08:39:21  opensuse/leap                                 15        db0649dcc151   2 weeks ago      113MB
08:39:21  quay.io/centos/centos                         stream8   1637482d9096   4 weeks ago      374MB
08:39:21  centos                                        7         eeb6ee3f44bd   18 months ago    204MB
```

In a job from 07.03 (I assume, when tests were still fine) I see:

```
07:13:36  REPOSITORY                                      TAG       IMAGE ID       CREATED          SIZE
07:13:36  eclipse/platformreleng-centos-gtk3-metacity     7         64c3783cd6dc   3 minutes ago    814MB
07:13:36  eclipse/platformreleng-centos-swt-build         8         3ba6cc303a12   5 minutes ago    1.43GB
07:13:36  eclipse/platformreleng-centos-swt-build         9         07444fef8621   6 minutes ago    1.41GB
07:13:36  eclipse/platformreleng-ubuntu-gtk3-metacity     20.04     e37ce6cd8eaf   6 minutes ago    644MB
07:13:36  eclipse/platformreleng-centos-gtk3-metacity     8         8f29bc3364f1   6 minutes ago    949MB
07:13:36  eclipse/platformreleng-opensuse-gtk3-metacity   15        e2028f5ce284   6 minutes ago    711MB
07:13:36  eclipse/platformreleng-ubuntu-gtk3-metacity     22.04     f38620db8b90   7 minutes ago    671MB
07:13:36  eclipse/platformreleng-ubuntu-gtk3-metacity     18.04     bd7e4b6447b6   7 minutes ago    555MB
07:13:36  eclipse/platformreleng-centos-gtk4-mutter       9         b6103ce574b7   9 minutes ago    910MB
07:13:36  eclipse/platformreleng-ubuntu-gtk3-metacity     jikespg   cf1832e36b00   13 minutes ago   413MB
07:13:36  ubuntu                                          20.04     61c45d0e9798   6 days ago       72.8MB
07:13:36  ubuntu                                          22.04     74f2314a03de   6 days ago       77.8MB
07:13:36  ubuntu                                          18.04     b89fba62bc15   6 days ago       63.1MB
07:13:36  quay.io/centos/centos                           stream9   6f41e24aa37b   6 days ago       155MB
07:13:36  opensuse/leap                                   15        db0649dcc151   7 days ago       113MB
07:13:36  quay.io/centos/centos                           stream8   1637482d9096   3 weeks ago      374MB
07:13:36  centos                                          7         eeb6ee3f44bd   17 months ago    204MB
```

Then in the build artifacts of job 498 I find this at the end of `eclipse.platform.releng.aggregator/cje-production/dockerfiles/swt_9_build.log`:

```
Failed:
  gcc-11.3.1-4.3.el9.x86_64                                                     
  gtk3-devel-3.24.31-2.el9.x86_64                                               
  java-17-openjdk-1:17.0.6.0.9-0.4.ea.el9.x86_64                                
  libXt-devel-1.2.0-6.el9.x86_64                                                
  libgweather-40.0-3.el9.x86_64                                                 
  mesa-libGL-devel-22.3.0-2.el9.x86_64                                          
  mesa-libGLU-devel-9.0.1-6.el9.x86_64                                          [91mError: Transaction failed
[0m
```

In the same log from job 495 I instead find this at the end:

```
Complete!
21 files removed
Removing intermediate container 02fcb17b1933
 ---> 59b822e43add
Step 7/14 : RUN localedef -i en_US -f UTF-8 en_US.UTF-8
 ---> Running in 7c0e23d743ce
Removing intermediate container 7c0e23d743ce
 ---> 3af82da3b56e
Step 8/14 : ENV LANG=en_US.UTF-8
 ---> Running in 59b633c7b382
Removing intermediate container 59b633c7b382
 ---> a4fa7a169eb1
Step 9/14 : ENV HOME=/home/vnc
 ---> Running in a91a1378b504
Removing intermediate container a91a1378b504
 ---> 5f6559886331
Step 10/14 : ENV DISPLAY :0
 ---> Running in b2bfc178f1f8
Removing intermediate container b2bfc178f1f8
 ---> d547eedb967c
Step 11/14 : RUN mkdir -p ${HOME}/.vnc && chmod -R 775 ${HOME}   && echo "123456" | vncpasswd -f > ${HOME}/.vnc/passwd   && chmod 600 ${HOME}/.vnc/passwd
 ---> Running in 8dbe86557a6b
Removing intermediate container 8dbe86557a6b
 ---> 1e1fd859cc04
Step 12/14 : COPY scripts/xstartup_metacity.sh ${HOME}/.vnc/xstartup.sh
 ---> 1db1f79ae4b6
Step 13/14 : RUN chgrp -R 0 ${HOME} && chmod -R g=u ${HOME}
 ---> Running in d198e820a1ba
Removing intermediate container d198e820a1ba
 ---> 54494127185b
Step 14/14 : USER 10001
 ---> Running in f8b668e8207d
Removing intermediate container f8b668e8207d
 ---> 07444fef8621
Successfully built 07444fef8621
Successfully tagged eclipse/platformreleng-centos-swt-build:9
~/jenkins/workspace/Build-Docker-images/eclipse.platform.releng.aggregator/cje-production/dockerfiles
```
