### ISSUE TITLE
4.29 I-Build: I20230609-1800 - BUILD FAILED

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#240]
See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/7/console

`addToComposite` task from ant runner started IDE with **Java 11** and as expected (most of the platform requires Java 17 meanwhile) this doesn't work. 

I have no idea how that worked before during 4.28 time (or did something changed in build scripts in 4.29?), but now obviously this doesn't work anymore:

```
01:26:55  --2023-06-09 19:26:55--  https://download.eclipse.org/eclipse/relengScripts/cje-production/scripts/addToComposite.xml
01:26:55  Resolving download.eclipse.org (download.eclipse.org)... 198.41.30.199
01:26:55  Connecting to download.eclipse.org (download.eclipse.org)|198.41.30.199|:443... connected.
01:26:55  HTTP request sent, awaiting response... 200 OK
01:26:55  Length: 816 [text/xml]
01:26:55  Saving to: ‘/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/addToComposite.xml’
01:26:55  
01:26:55       0K                                                       100%  459M=0s
01:26:55  
01:26:55  2023-06-09 19:26:55 (459 MB/s) - ‘/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/addToComposite.xml’ saved [816/816]
01:26:55  
01:26:58  Install location:
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/
01:26:58  Configuration file:
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/configuration/config.ini loaded
01:26:58  Configuration location:
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/configuration/
01:26:58  Framework located:
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/plugins/org.eclipse.osgi_3.18.400.v20230509-2241.jar
01:26:58  Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
01:26:58  	eclipse.properties not found
01:26:58  Framework classpath:
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/plugins/org.eclipse.osgi_3.18.400.v20230509-2241.jar
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/plugins/
01:26:58      file:/home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
01:26:59  Debug options:
01:26:59      file:/opt/public/hipp/homes/genie.releng/.options not found
01:27:00  Time to load bundles: 174
01:27:06  !SESSION 2023-06-09 19:26:58.413 -----------------------------------------------
01:27:06  eclipse.buildId=4.28.0.I20230605-0440
01:27:06  java.version=11.0.10
01:27:06  java.vendor=Oracle Corporation
01:27:06  BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en
01:27:06  Framework arguments:  -application org.eclipse.ant.core.antRunner -file /home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/addToComposite.xml addToComposite -Drepodir=/home/data/httpd/download.eclipse.org/eclipse/updates/4.29-I-builds -Dcomplocation=I20230609-1800
01:27:06  Command-line arguments:  -consolelog -debug -data /home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/workspace-antRunner -application org.eclipse.ant.core.antRunner -file /home/data/httpd/download.eclipse.org/eclipse/workingDir/Builds/I-build-4.29-7/addToComposite.xml addToComposite -Drepodir=/home/data/httpd/download.eclipse.org/eclipse/updates/4.29-I-builds -Dcomplocation=I20230609-1800
01:27:06  
01:27:06  !ENTRY org.eclipse.ant.core 4 0 2023-06-09 19:27:06.629
01:27:06  !MESSAGE FrameworkEvent ERROR
01:27:06  !STACK 0
01:27:06  org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ant.core [39]
01:27:06    Unresolved requirement: Require-Bundle: org.eclipse.core.variables; bundle-version="[3.1.0,4.0.0)"
01:27:06      -> Bundle-SymbolicName: org.eclipse.core.variables; bundle-version="3.6.0.v20230317-0802"; singleton:="true"
01:27:06         org.eclipse.core.variables [58]
01:27:06           Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
01:27:06           Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
01:27:06             -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.27.0.v20230515-1719"; singleton:="true"
01:27:06                org.eclipse.core.runtime [57]
01:27:06                  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
01:27:06                  Unresolved requirement: Require-Bundle: org.eclipse.core.jobs; bundle-version="[3.13.0,4.0.0)"; visibility:="reexport"
01:27:06                    -> Bundle-SymbolicName: org.eclipse.core.jobs; bundle-version="3.14.0.v20230317-0901"; singleton:="true"
01:27:06                       org.eclipse.core.jobs [53]
01:27:06                         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
01:27:06                  Unresolved requirement: Require-Bundle: org.eclipse.core.contenttype; bundle-version="[3.8.0,4.0.0)"; visibility:="reexport"
01:27:06                    -> Bundle-SymbolicName: org.eclipse.core.contenttype; bundle-version="3.9.0.v20230412-0829"; singleton:="true"
01:27:06                       org.eclipse.core.contenttype [43]
01:27:06                         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
01:27:06    Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.25.0,4.0.0)"
01:27:06      -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.27.0.v20230515-1719"; singleton:="true"
01:27:06  
01:27:06  	at org.eclipse.osgi.container.Module.start(Module.java:463)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
01:27:06  	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
01:27:06  	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
01:27:06  	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
01:27:06  	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```
..., 
tons of similar errors after and finally  

```
01:27:08  !ENTRY org.eclipse.osgi 4 0 2023-06-09 19:27:08.549
01:27:08  !MESSAGE Application error
01:27:08  !STACK 1
01:27:08  java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
01:27:08  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
01:27:08  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
01:27:08  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
01:27:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:27:08  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:27:08  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:27:08  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:27:08  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
01:27:08  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
01:27:08  	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
01:27:08  	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
[Pipeline] }
01:27:09  Executing sh script inside container jnlp of pod aggrbuild-pod-n7t9c-6hwb0
01:27:09  Executing command: "ssh-agent" "-k" 
01:27:09  exit
01:27:09  unset SSH_AUTH_SOCK;
01:27:09  unset SSH_AGENT_PID;
01:27:09  echo Agent pid 24141 killed;
01:27:09  [ssh-agent] Stopped.
[Pipeline] // sshagent
[Pipeline] }
[Pipeline] // container
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Trigger tests)
Stage "Trigger tests" skipped due to earlier failure(s)
```

**Comment by iloveeclipse** [comment]
I've re-triggered build to see if that was a random fail (for whatever reason): https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/8/

**Comment by iloveeclipse** [comment]
Hmm. I wonder if that is something related to the installed Java versions, I see this "collect results" build failing too:

https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/1494/console

```
-installIU org.eclipse.platform.ide,org.eclipse.pde.api.tools,org.eclipse.releng.build.tools.feature.feature.group,org.eclipse.wtp.releng.tools.feature.feature.group
09:07:36 -destination /home/data/httpd/download.eclipse.org/eclipse/workingDir/ep-collectResults-1494/basebuilder
09:07:36 -profile SDKProfile
09:07:36 -vm /usr/bin/java
09:07:36 -vmargs
09:07:36 -Dosgi.requiredJavaVersion=17
09:07:36 -Dosgi.dataAreaRequiresExplicitInit=true
09:07:36 -Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
09:07:36 -Xms40m
09:07:36 -Xmx512m
09:07:36 --add-modules=ALL-SYSTEM
09:07:36 -jar /home/data/httpd/download.eclipse.org/eclipse/workingDir/ep-collectResults-1494/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar 
09:07:36 Incompatible JVM:
09:07:36 Version 11.0.19 of the JVM is not suitable for this product. Version: 17 or greater is required.
09:07:36 Build step 'Execute shell' marked build as failure
```

**Comment by iloveeclipse** [comment]
Can it be, we can't find Java 17 anymore? Do we have any changes in the related workstations?

**Comment by merks** [comment]
Probably you should change the configuration which currently asks for Java 11 not Java 17:

![image](https://github.com/eclipse-platform/eclipse.platform.releng/assets/208716/ff2ea14e-3cf3-4704-8d90-39d94b8e1257)

https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/configure

**Comment by merks** [comment]
It's probably using some tool from the 4.28 release while previously it was using some tool from the 4.27 release which still ran with Java 11.  it's just a theory...

**Comment by iloveeclipse** [comment]
> Probably you should change the configuration which currently asks for Java 11 not Java 17

That wasn't changed recently, but sure, we can try.

**Comment by iloveeclipse** [comment]
> That wasn't changed recently, but sure, we can try.

Changed config and restarted the last build: same issue.

**Comment by merks** [comment]
I see it logging this which seems not a good one on the 
```
09:27:16 Start VM: /usr/bin/java
```
It does specify this path when running:
```
09:27:15 + ssh genie.releng@projects-storage.eclipse.org PATH=/opt/tools/java/openjdk/jdk-17/17/bin:/opt/tools/java/openjdk/jdk-17/latest/bin:/opt/tools/java/openjdk/jdk-17/latest/bin:/home/jenkins/agent/tools/hudson.tasks.Ant_AntInstallation/apache-ant-latest/bin:/opt/tools/java/openjdk/jdk-17/latest/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /home/data/httpd/download.eclipse.org/eclipse/workingDir/ep-collectResults-1495/eclipse/eclipse -nosplash -debug -consolelog -data /home/data/httpd/download.eclipse.org/eclipse/workingDir/ep-collectResults-1495/workspace-toolsinstall -application org.eclipse.equinox.p2.director -repository https://download.eclipse.org/eclipse/updates/4.29-I-builds/,https://download.eclipse.org/eclipse/updates/buildtools/,https://download.eclipse.org/webtools/downloads/drops/R3.27.0/R-3.27.0-20220829002010/repositoryunittests/ -installIU org.eclipse.platform.ide,org.eclipse.pde.api.tools,org.eclipse.releng.build.tools.feature.feature.group,org.eclipse.wtp.releng.tools.feature.feature.group -destination /home/data/httpd
```
But I guess the PATH is not correct for that host where it's running.  I guess that used to work though...

**Comment by iloveeclipse** [comment]
See similar issue we had in the past: https://github.com/eclipse-platform/eclipse.platform.releng/issues/217 and especially https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2835 that says JDK 17 on `projects-storage` should be `/opt/public/common/java/openjdk/jdk-17_x64-latest`.

In this concrete case looks like some environment or build script change finally caused latest 4.28 SDK builds to be used for building 4.29, and `antRunner` application requires Java 17 since 4.28.

I've pushed https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1137

**Comment by iloveeclipse** [comment]
Note: I've manually updated `ep-collectResults` job ( https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/jobConfigHistory/showDiffFiles?timestamp1=2023-06-10_03-26-35&timestamp2=2023-06-11_03-45-41 ) to use `/opt/public/common/java/openjdk/jdk-17_x64-latest/bin`  in `PATH` and next job execution succeeded with that: https://ci.eclipse.org/releng/job/Releng/job/ep-collectResults/1496/

**Comment by iloveeclipse** [comment]
Merged https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1137 , going to trigger new SDK build.

**Comment by iloveeclipse** [comment]
> Merged [eclipse-platform/eclipse.platform.releng.aggregator#1137](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1137) , going to trigger new SDK build.

Build succeeded: https://download.eclipse.org/eclipse/downloads/drops4/I20230611-0410
